### ISSUE TITLE
Possible API name suggestion 

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-iot-middleware-freertos#127]
AzureIoTHubClient_GetDeviceTwin -> AzureIoTHubClient_RequestDeviceTwinAsync | AzureIoTHubClient_RequestDeviceTwin

PR: https://github.com/Azure-Samples/iot-middleware-freertos-samples/pull/1/files#r640945672

**Comment by hihigupt** [comment]
MethodResponse input for AzureIoTHubClient_SendMethodResponse https://github.com/Azure-Samples/iot-middleware-freertos-samples/pull/1/files#r640939740

**Comment by jspaith** [comment]
Yes, I prefer the word "Request".  The "Async" at end makes sense to me too; it certainly follows C SDK behavior which always made sense to me.
