### ISSUE TITLE
Connection errors every 65 minutes

### ISSUE THREAD

**Issue by rtheil-growlink** [Azure/azure-iot-middleware-freertos#234]
I've got another issue here that I am guessing is related to the SAS token, as this occurs every 65 minutes. Very similar to what I saw with the c sdk. When this happens I'm disconnecting and reconnecting and that seems to cure, but I figure there's probably something I'm missing that would prevent these errors completely.

```
E (51768706) tls_freertos: Reading failed, errno= 128
E (51768706) MQTT: A single byte was not read from the transport: transportStatus=-1.
E (51768716) MQTT: Receiving incoming packet length failed. Status=MQTTRecvFailed
E (51768726) MQTT: Exiting process loop due to failure: ErrorStatus=MQTTRecvFailed
E (51768726) AZ IOT: AzureIoTMQTT_ProcessLoop failed: ProcessLoopDuration=500, MQTT error=0x00000004
```

**Comment by danewalton** [comment]
Yes this is going to be related to the SAS token at that point. If the connection expires, the TLS connection will be severed and you won't be able to receive bytes on the line. The MQTT error number `4` is related to an inability to "`recv`". If you wanted to refresh the token before the connection expires, you could do it before the theoretical expiration (say every 50 minutes or so), and do a clean shutdown then reconnect.

**Comment by rtheil-growlink** [comment]
Thanks, Dane. How do I force the token refresh without doing a full disconnect/reconnect process?

**Comment by rtheil-growlink** [comment]
OK, I think that makes sense. Can I just call _Disconnect() and _Connect()? or do I need to go through the whole process of unsubscribe from properties/command and start all over?

**Comment by danewalton** [comment]
The TLS and the MQTT must both be reconnected but yes you have the right idea. As long as you don't pass `cleanSession` as true for the connect, you shouldn't need to re-subscribe. I have the below basic scenario working on our Linux sample. Please see the `NEW BITS` section to see how I recreated this scenario:

```c
        bool xDidDisconnect = false;
        /* Publish messages with QoS1, send and process Keep alive messages. */
        for( lPublishCount = 0; lPublishCount < lMaxPublishCount; lPublishCount++ )
        {
            ulScratchBufferLength = snprintf( ( char * ) ucScratchBuffer, sizeof( ucScratchBuffer ),
                                              sampleazureiotMESSAGE, lPublishCount );
            xResult = AzureIoTHubClient_SendTelemetry( &xAzureIoTHubClient,
                                                       ucScratchBuffer, ulScratchBufferLength,
                                                       &xPropertyBag, eAzureIoTHubMessageQoS1, NULL );
            configASSERT( xResult == eAzureIoTSuccess );

            LogInfo( ( "Attempt to receive publish message from IoT Hub.\r\n" ) );
            xResult = AzureIoTHubClient_ProcessLoop( &xAzureIoTHubClient,
                                                     sampleazureiotPROCESS_LOOP_TIMEOUT_MS );
            configASSERT( xResult == eAzureIoTSuccess );

            if( lPublishCount % 2 == 0 )
            {
                /* Send reported property every other cycle */
                ulScratchBufferLength = snprintf( ( char * ) ucScratchBuffer, sizeof( ucScratchBuffer ),
                                                  sampleazureiotPROPERTY, lPublishCount / 2 + 1 );
                xResult = AzureIoTHubClient_SendPropertiesReported( &xAzureIoTHubClient,
                                                                    ucScratchBuffer, ulScratchBufferLength,
                                                                    NULL );
                configASSERT( xResult == eAzureIoTSuccess );
            }

            // NEW BITS
            if (!xDidDisconnect)
            {
                LogInfo( ( "Disconnecting from %s.\r\n", pucIotHubHostname ) );
                xResult = AzureIoTHubClient_Disconnect( &xAzureIoTHubClient );
                configASSERT( xResult == eAzureIoTSuccess );

                vTaskDelay( sampleazureiotDELAY_BETWEEN_PUBLISHES_TICKS );

                ulStatus = prvConnectToServerWithBackoffRetries( ( const char * ) pucIotHubHostname,
                                                         democonfigIOTHUB_PORT,
                                                         &xNetworkCredentials, &xNetworkContext );

                LogInfo( ( "Creating an MQTT connection to %s.\r\n", pucIotHubHostname ) );
                xResult = AzureIoTHubClient_Connect( &xAzureIoTHubClient,
                                                    false, &xSessionPresent,
                                                    sampleazureiotCONNACK_RECV_TIMEOUT_MS );
                configASSERT( xResult == eAzureIoTSuccess );
                
                xDidDisconnect = true;
            }
            // END NEW BITS


            /* Leave Connection Idle for some time. */
            LogInfo( ( "Keeping Connection Idle...\r\n\r\n" ) );
            vTaskDelay( sampleazureiotDELAY_BETWEEN_PUBLISHES_TICKS );
        }
```

**Comment by rtheil-growlink** [comment]
Excellent example. Got that implemented perfectly. Thanks again, Dane.

**Comment by rtheil-growlink** [comment]
Hey, just an update on this. After some testing, I found that without calling TLS_Socket_Disconnect() after AzureIoTHubClient_Disconnect(), I'd eventually run out of heap memory. Sometimes even after a few disconnections and reconnections I'd get esp TLS errors that it couldn't malloc. I set up a test for the last 5 days while I was out of town after adding TLS_Socket_Disconnect() and had it reconnecting every 2 minutes. Worked like a charm.

**Comment by LucasIssardWatts** [comment]
Hi Dane and Ricky. I had the same problem related to the SAS token, your solution helped me a lot ! Thank you very much !

However, I still have a memory leak when refreshing the token.
After some research, I notice that `TLS_Socket_Connect` (called in `prvConnectToServerWithBackoffRetries`) allocates more heap memory (almost 37.5 kB) than `TLS_Socket_Disconnect` frees (only 31 kB). The difference between the two is lost (6.5 kB).
After several refreshes (several hours), I reach the end of the memory and my ESP32 reboots...

According to your last messages, you don't seem to have this problem. Do you have an explanation ? Have I forgotten something ?

Here is a snippet of my refresh token function :
````c
void refresh_sas_token(AzureIoTHubClient_t *pxAzureIoTHubClient, NetworkContext_t *pxNetworkContext, NetworkCredentials_t *pxNetworkCredentials)
{
    AzureIoTResult_t xResult;
    bool xSessionPresent;

    /* Disconnect */
    xResult = AzureIoTHubClient_Disconnect( pxAzureIoTHubClient );
    configASSERT( xResult == eAzureIoTSuccess );

    TLS_Socket_Disconnect( pxNetworkContext );    // Frees 31 kB of heap memory

    vTaskDelay( sampleazureiotDELAY_BETWEEN_PUBLISHES_TICKS );

    /* Reconnect */
    prvConnectToServerWithBackoffRetries( (const char *)democonfigHOSTNAME, democonfigIOTHUB_PORT, pxNetworkCredentials, pxNetworkContext );    // Allocates 37.5 kB of heap memory (TLS_Socket_Connect)

    xResult = AzureIoTHubClient_Connect( pxAzureIoTHubClient, false, &xSessionPresent, sampleazureiotCONNACK_RECV_TIMEOUT_MS );
    configASSERT( xResult == eAzureIoTSuccess );
}
````

For information :
- Compiled for ESP32 with ESP-IDF v4.4
- `refresh_sas_token` function is called in `prvAzureDemoTask`, immediatly after `AzureIoTHubClient_ProcessLoop`, in the project `iot-middleware-freertos-samples\demos\projects\ESPRESSIF\esp32` (`AzureIoTHubClient_SendTelemetry` and `AzureIoTHubClient_SendPropertiesReported` not used)

**Comment by danewalton** [comment]
I have a feeling it might be related to this?

https://github.com/Azure-Samples/iot-middleware-freertos-samples/issues/338

**Comment by rtheil-growlink** [comment]
@LucasIssardWatts There's a couple things to check. Here's my reconnect procedure. I found a couple things that had to be done in order to eliminate leaks.

```
bool AzureService::reconnect()
{
#ifdef AZURE_DEBUG
    ESP_LOGW(TAG, "----------------------------------------------------------------------------reconnect()");
#endif
    lock("reconnect");

    //disconnect
    AzureIoTResult_t xResult = AzureIoTHubClient_Disconnect(&xAzureIoTHubClient);
    checkAzureError(xResult, "reconnect:AzureIoTHubClient_Disconnect");
    TLS_Socket_Disconnect(&xNetworkContext);

    //connect
    uint32_t ulStatus = connectToServer((const char *)_hostname, 
                                        8883, &xNetworkCredentials,
                                        &xNetworkContext);
    if (!checkAzureError(ulStatus, "AzureService::connectToServer"))
    {
        unlock("reconnect->conenctToServer fail");
        _connected = false;
        return false;
    }

    xResult = AzureIoTHubClient_Connect(&xAzureIoTHubClient,
                                        false, &xSessionPresent,
                                        CONNACK_RECV_TIMEOUT_MS);
    if (!checkAzureError(xResult, "reconnect:AzureIoTHubClient_Connect"))
    {
        unlock("reconnect-> _Connect fail");
        _connected = false;
        return false;
    }
    unlock("reconnect");

    _connectionTime = millis();
    return true;
}
```

Also, I just found a memory leak a couple days ago in the change Dane made to fix the multi certificate setup in ESP for baltimore/digicert setup. In the demo file transport_tls_esp32.c in TLS_Socket_Connect() function, there's a call to init the ca store. It inits that every time, which takes heap over and over again. Here's my changes:

Top of file:
```
bool ca_store_set = false;
```

TLS_Socket_Connect() function:
```
if ( pNetworkCredentials->pucRootCa && !ca_store_set )
    {
        esp_tls_set_global_ca_store( ( const unsigned char * ) pNetworkCredentials->pucRootCa, pNetworkCredentials->xRootCaSize );
        ca_store_set = true;
    }
```

It's like 4-5k heap every single time it's run. For testing, I set my reconnect time to 20 seconds so it'd just repeatedly connect. Normally it's 50 minutes.

**Comment by LucasIssardWatts** [comment]
Hi. The solution given here https://github.com/Azure-Samples/iot-middleware-freertos-samples/issues/338#issuecomment-1568808505 worked perfectly. Thanks !

**Comment by wreyford** [comment]
Hi, @rtheil-growlink , is there any posibility that you can share your  **checkAzureError** `checkAzureError(xResult, "reconnect:AzureIoTHubClient_Disconnect"); `This is another part of the equation, and I have been struggling with a well designed way of getting rid of all the asserts in the example code, and it looks like you have got it sorted.

**Comment by rtheil-growlink** [comment]
Sure thing. Nothing too complicated here, just some centralized logging and checks for situations that rarely occur. System.memlog() is just a function I use to constantly log memory usage, when needed, so I'll include that also.

```c
bool AzureService::checkAzureError(uint32_t result, const char *where)
{
    char logTitle[70];
    sprintf(logTitle, "AzureService.checkAzureError: %s", where);
    System.memLog(logTitle);

    if (result != 0)
    {
        ESP_LOGE(TAG, "checkAzureError at %s: result: %d", where, result);
        return false;
    }

#ifdef AZURE_DEBUG
    ESP_LOGI(TAG, "checkAzureError at %s, result: %i", where, result);
#endif

    return true;
}

void SystemClass::memLog(const char *what)
{
#ifdef MEMORY_LOG
    ESP_LOGW("memLog", "%s: TaskMinFree: %d, HeapFree: %d, maxHeapFree: %d", what, uxTaskGetStackHighWaterMark(NULL), freeMemory(), esp_get_minimum_free_heap_size());
#endif
}
```
