### ISSUE TITLE
Is this project still under maintenance?

### ISSUE THREAD

**Issue by thomasweichselbaumer** [Azure/azure-iot-middleware-freertos#324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

master

### Description of the issue

Our dev-team want to move from **azure-iot-sdk-c** to **Azure Iot Middleware for FreeRTOS** or **azure-sdk-for-c** to save resourcess on our embedded target. Now we are not sure if this is the right choice because there is no commit in the last year. The last release is mor than 2 years ago. Is this project still under maintenance?

@danewalton i saw you in the video. Can you tell use something about that? Which SDK would you recommend on an embedded target like the esp32?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thomasweichselbaumer** [comment]
We also have concern about following remark under porting mqtt: **THIS FEATURE IS IN PREVIEW AND THE API IS SUBJECT TO CHANGE**

**Comment by ericwol-msft** [comment]
Yes it is. Is there anything particular you need?

> THIS FEATURE IS IN PREVIEW AND THE API IS SUBJECT TO CHANGE

 This is referring to the MQTT abstraction layer feature and not the SDK. Currently we don't fully support swapping out the MQTT layer from CoreMQTT.

**Comment by ericwol-msft** [comment]
Also, please note, this is a freeRTOS wapper for the actual embedded IoT SDK. This SDK handles the freeRTOS interaction. The IoT hub features are implemented and exposed on the IoT Hub SDK. 

https://github.com/Azure/azure-sdk-for-c

**Comment by ericwol-msft** [comment]
closing this issue
