### ISSUE TITLE
Inspect packet to see if ack was successful

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-iot-middleware-freertos#65]
`TODO` tag here:
https://github.com/Azure/azure-iot-middleware-freertos/blob/8de270669263019f735b59dfd1d7bcdf6a0521a3/source/azure_iot_hub_client.c#L90-L91

**Comment by hihigupt** [comment]
Is this required? Tcp connection will be broken if the subscribe fails

**Comment by danewalton** [comment]
closed with https://github.com/Azure/azure-iot-middleware-freertos/pull/89
